<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Saved</name>
   <tag></tag>
   <elementGuidId>425b744b-e9eb-469b-8484-36b4c17516d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tp-saved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='saved']/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15984a93-ab59-4255-9984-6698a0092482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-saved</value>
      <webElementGuid>76ca89db-6d5e-4499-b62b-3a8854528eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saved</value>
      <webElementGuid>846bbadd-4d29-4ac6-93de-efa00197fb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saved&quot;)/h3[1]/span[@class=&quot;tp-saved&quot;]</value>
      <webElementGuid>2f0cf8c3-fae4-4418-a551-ff9dc443c47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='saved']/h3/span</value>
      <webElementGuid>4b5ab3f9-27f1-4e76-bee6-c6f75a12087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid phone number'])[1]/following::span[1]</value>
      <webElementGuid>65607ce0-1b5b-4d53-baff-3950126ad1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone:'])[1]/following::span[1]</value>
      <webElementGuid>0c3677f1-36fd-4b6a-a942-f1cbb43128ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>745db7ba-debe-4faf-aa8b-59fc955e5119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[1]</value>
      <webElementGuid>d16dc8e6-254c-4711-99fa-98d73fd6692e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saved']/parent::*</value>
      <webElementGuid>517205bb-6d69-4761-95ab-8d19d4e3736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>00ede478-97ce-4f39-bbdb-845fe631852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Saved' or . = 'Saved')]</value>
      <webElementGuid>97f68997-6e07-49f5-aa18-d06a6154e6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
